tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "rgb(var(--c-surface) / <alpha-value>)",
        "surface-bright": "rgb(var(--c-surface-bright) / <alpha-value>)",
        "surface-dim": "rgb(var(--c-surface-dim) / <alpha-value>)",
        "background": "rgb(var(--c-background) / <alpha-value>)",
        "on-surface": "rgb(var(--c-on-surface) / <alpha-value>)",
        "on-background": "rgb(var(--c-on-background) / <alpha-value>)",
        "surface-variant": "rgb(var(--c-surface-variant) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--c-on-surface-variant) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--c-surface-container-lowest) / <alpha-value>)",
        "surface-container-low": "rgb(var(--c-surface-container-low) / <alpha-value>)",
        "surface-container": "rgb(var(--c-surface-container) / <alpha-value>)",
        "surface-container-high": "rgb(var(--c-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--c-surface-container-highest) / <alpha-value>)",
        "surface-tint": "rgb(var(--c-surface-tint) / <alpha-value>)",
        "outline": "rgb(var(--c-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--c-outline-variant) / <alpha-value>)",
        "primary": "rgb(var(--c-primary) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--c-primary-container) / <alpha-value>)",
        "on-primary-container": "rgb(var(--c-on-primary-container) / <alpha-value>)",
        "primary-fixed": "rgb(var(--c-primary-fixed) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--c-primary-fixed-dim) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--c-on-primary-fixed) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)",
        "inverse-primary": "rgb(var(--c-inverse-primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--c-primary-hover) / <alpha-value>)",
        "primary-active": "rgb(var(--c-primary-active) / <alpha-value>)",
        "inverse-surface": "rgb(var(--c-inverse-surface) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--c-inverse-on-surface) / <alpha-value>)",
        "error": "rgb(var(--c-error) / <alpha-value>)",
        "on-error": "rgb(var(--c-on-error) / <alpha-value>)",
        "error-container": "rgb(var(--c-error-container) / <alpha-value>)",
        "on-error-container": "rgb(var(--c-on-error-container) / <alpha-value>)",
        "secondary": "rgb(var(--c-secondary) / <alpha-value>)",
        "on-secondary": "rgb(var(--c-on-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--c-secondary-container) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--c-on-secondary-container) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--c-secondary-fixed) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--c-secondary-fixed-dim) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--c-on-secondary-fixed) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)",
        "tertiary": "rgb(var(--c-tertiary) / <alpha-value>)",
        "on-tertiary": "rgb(var(--c-on-tertiary) / <alpha-value>)",
        "tertiary-container": "rgb(var(--c-tertiary-container) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--c-on-tertiary-container) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--c-tertiary-fixed) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)",
        "on-tertiary-fixed": "rgb(var(--c-on-tertiary-fixed) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)",
        "warning": "rgb(var(--c-warning) / <alpha-value>)",
        "on-warning": "rgb(var(--c-on-warning) / <alpha-value>)",
        "warning-container": "rgb(var(--c-warning-container) / <alpha-value>)",
        "on-warning-container": "rgb(var(--c-on-warning-container) / <alpha-value>)"
      },
      boxShadow: {
        "navbar": "0 1px 8px rgb(var(--c-shadow) / var(--shadow-strength))"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "margin": "2rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "headline-sm": ["Cairo", "sans-serif"],
        "label-sm": ["Cairo", "sans-serif"],
        "headline-md": ["Cairo", "sans-serif"],
        "headline-lg": ["Cairo", "sans-serif"],
        "headline-lg-mobile": ["Cairo", "sans-serif"],
        "price-display": ["Cairo", "sans-serif"],
        "body-sm": ["Cairo", "sans-serif"],
        "body-lg": ["Cairo", "sans-serif"],
        "label-md": ["Cairo", "sans-serif"],
        "label-lg": ["Cairo", "sans-serif"],
        "body-md": ["Cairo", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["18px", {"lineHeight": "26px", "letterSpacing": "0", "fontWeight": "700"}],
        "headline-lg-mobile": ["26px", {"lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0", "fontWeight": "600"}],
        "headline-md": ["22px", {"lineHeight": "30px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.015em", "fontWeight": "800"}],
        "price-display": ["18px", {"lineHeight": "24px", "letterSpacing": "0", "fontWeight": "700"}],
        "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "26px", "fontWeight": "400"}],
        "label-md": ["13px", {"lineHeight": "19px", "fontWeight": "600"}],
        "label-lg": ["15px", {"lineHeight": "22px", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "22px", "fontWeight": "400"}]
      }
    }
  }
}